require 'rubygems'
require 'bundler/setup'
require_relative 'keys.local.rb'
require 'unicorn'
require 'rack/cors'
require 'grape'
require 'json'
require 'time'
require 'net/http'
require 'uri'
require 'telegram/bot' if BOT_TYPE=="TELEGRAM"
require 'logger'
require 'ostruct'
require 'open-uri'
require 'rest_client'
