#### BOT CONFIG ####
BOT_TYPE="TELEGRAM" # POSSIBLE VALUES ARE TELEGRAM OR FBMESSENGER
WEBHOOK_PREFIX=""
SECRET=""

#### TELEGRAM ####
TGTOKEN=""

#### FB MESSENGER ####
FBPAGEACCTOKEN="" # FB Page token
